/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    topics: Topic;
    'timeline-events': TimelineEvent;
    'media-outlets': MediaOutlet;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    'timeline-events': TimelineEventsSelect<false> | TimelineEventsSelect<true>;
    'media-outlets': MediaOutletsSelect<false> | MediaOutletsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'es' | 'ja' | 'ko' | 'zh')
    | ('en' | 'es' | 'ja' | 'ko' | 'zh')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es' | 'ja' | 'ko' | 'zh';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: string;
  title: string;
  slug: string;
  /**
   * Toggle to show/hide this topic on the globe in View A
   */
  showInViewA?: boolean | null;
  summary?: string | null;
  type: 'environment' | 'technology' | 'economy' | 'health' | 'conflict' | 'science';
  location: {
    lat: number;
    lon: number;
  };
  /**
   * Search engine optimization and social media metadata
   */
  seo?: {
    /**
     * Title displayed in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string | null;
    /**
     * The preferred URL for this content (for duplicate content handling)
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
    openGraph?: {
      /**
       * Title for Facebook/LinkedIn shares (defaults to Meta Title if empty)
       */
      ogTitle?: string | null;
      /**
       * Description for Facebook/LinkedIn shares
       */
      ogDescription?: string | null;
      /**
       * Image for social shares (1200x630px recommended)
       */
      ogImage?: (string | null) | Media;
      ogType?: ('article' | 'website' | 'profile') | null;
    };
    twitter?: {
      twitterCard?: ('summary' | 'summary_large_image') | null;
      /**
       * Title for Twitter shares (defaults to Meta Title if empty)
       */
      twitterTitle?: string | null;
      /**
       * Description for Twitter shares
       */
      twitterDescription?: string | null;
      /**
       * Image for Twitter shares (use OG Image if not set)
       */
      twitterImage?: (string | null) | Media;
      /**
       * @username of the content creator
       */
      twitterCreator?: string | null;
    };
    /**
     * Schema.org structured data for rich search results
     */
    structuredData?: {
      schemaType?: ('Article' | 'NewsArticle' | 'Event' | 'Organization' | 'WebPage') | null;
      author?: string | null;
      publisher?: string | null;
      datePublished?: string | null;
      dateModified?: string | null;
      /**
       * Override with custom JSON-LD (advanced users only)
       */
      customJsonLd?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events".
 */
export interface TimelineEvent {
  id: string;
  /**
   * The parent topic this event belongs to
   */
  topic: string | Topic;
  title: string;
  cardTitle?: string | null;
  cardSubtitle?: string | null;
  cardDetailedText?: string | null;
  date: string;
  mediaSource?: string | null;
  newsPerspective?: string | null;
  mediaBias?: string | null;
  diverseViewpoint?: string | null;
  order?: number | null;
  /**
   * URL to the original news article
   */
  sourceUrl?: string | null;
  /**
   * Sentiment score from NewsAPI (-1 to 1)
   */
  sentiment?: number | null;
  /**
   * Source of the data (e.g., "manual", "newsapi")
   */
  apiSource?: string | null;
  /**
   * Actual publication date from news source
   */
  publishedDate?: string | null;
  /**
   * Search engine optimization and social media metadata
   */
  seo?: {
    /**
     * Title displayed in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string | null;
    /**
     * The preferred URL for this content (for duplicate content handling)
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    noFollow?: boolean | null;
    openGraph?: {
      /**
       * Title for Facebook/LinkedIn shares (defaults to Meta Title if empty)
       */
      ogTitle?: string | null;
      /**
       * Description for Facebook/LinkedIn shares
       */
      ogDescription?: string | null;
      /**
       * Image for social shares (1200x630px recommended)
       */
      ogImage?: (string | null) | Media;
      ogType?: ('article' | 'website' | 'profile') | null;
    };
    twitter?: {
      twitterCard?: ('summary' | 'summary_large_image') | null;
      /**
       * Title for Twitter shares (defaults to Meta Title if empty)
       */
      twitterTitle?: string | null;
      /**
       * Description for Twitter shares
       */
      twitterDescription?: string | null;
      /**
       * Image for Twitter shares (use OG Image if not set)
       */
      twitterImage?: (string | null) | Media;
      /**
       * @username of the content creator
       */
      twitterCreator?: string | null;
    };
    /**
     * Schema.org structured data for rich search results
     */
    structuredData?: {
      schemaType?: ('Article' | 'NewsArticle' | 'Event' | 'Organization' | 'WebPage') | null;
      author?: string | null;
      publisher?: string | null;
      datePublished?: string | null;
      dateModified?: string | null;
      /**
       * Override with custom JSON-LD (advanced users only)
       */
      customJsonLd?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-outlets".
 */
export interface MediaOutlet {
  id: string;
  name: string;
  /**
   * Emoji icon or URL to icon image
   */
  icon: string;
  /**
   * Determines which sidebar the outlet appears in
   */
  region: 'international' | 'us';
  /**
   * Link to the media outlet website
   */
  url?: string | null;
  /**
   * Order in which to display (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'timeline-events';
        value: string | TimelineEvent;
      } | null)
    | ({
        relationTo: 'media-outlets';
        value: string | MediaOutlet;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showInViewA?: T;
  summary?: T;
  type?: T;
  location?:
    | T
    | {
        lat?: T;
        lon?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
        openGraph?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              ogType?: T;
            };
        twitter?:
          | T
          | {
              twitterCard?: T;
              twitterTitle?: T;
              twitterDescription?: T;
              twitterImage?: T;
              twitterCreator?: T;
            };
        structuredData?:
          | T
          | {
              schemaType?: T;
              author?: T;
              publisher?: T;
              datePublished?: T;
              dateModified?: T;
              customJsonLd?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events_select".
 */
export interface TimelineEventsSelect<T extends boolean = true> {
  topic?: T;
  title?: T;
  cardTitle?: T;
  cardSubtitle?: T;
  cardDetailedText?: T;
  date?: T;
  mediaSource?: T;
  newsPerspective?: T;
  mediaBias?: T;
  diverseViewpoint?: T;
  order?: T;
  sourceUrl?: T;
  sentiment?: T;
  apiSource?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
        openGraph?:
          | T
          | {
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              ogType?: T;
            };
        twitter?:
          | T
          | {
              twitterCard?: T;
              twitterTitle?: T;
              twitterDescription?: T;
              twitterImage?: T;
              twitterCreator?: T;
            };
        structuredData?:
          | T
          | {
              schemaType?: T;
              author?: T;
              publisher?: T;
              datePublished?: T;
              dateModified?: T;
              customJsonLd?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-outlets_select".
 */
export interface MediaOutletsSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  region?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}